### ISSUE TITLE
Add loading icon to the modal content container in backend

### ISSUE THREAD

**Issue by MDevster** [contao-components/simplemodal#3]
We have from time to time back end routes that are displayed via the simple modal and load a little longer.
Would it be conceivable that we simply set the existing [loading icon](https://github.com/contao-components/simplemodal/blob/2.x/images/loader.gif) via CSS? Or the one from Contao ;)

Example
```
.simple-modal .simple-modal-body div.contents {
  background: url(/system/themes/flexible/icons/loading.svg) no-repeat 50% 50px;
}
```

Result

[Dateiverwaltung-pdir-dev.webm](https://user-images.githubusercontent.com/10244240/210850802-2907f141-863e-47d1-b0d8-9e1b9a827d3a.webm)

Even nicer would be something like Bricks for the loading icon in the Contao colors
https://loading.io/spinner/bricks/-rectangle-block-brick-square-rotate

**Comment by leofeyer** [comment]
Version 3 includes a loader icon. Would this be sufficient?

**Comment by MDevster** [comment]
That would be fine.
